### ISSUE TITLE
consider dropping tensorflow

### ISSUE THREAD

**Issue by bcdarwin** [LKS-CHART/medical-imaging-nix#24]
justifications:
 - it takes a long time to build
 - it adds ~1GB of space
 - it probably slows down imports of various DL libraries such as Huggingface that will import it if it's present
 - we don't use it
 - even though it's arguably more self-contained than torch we don't have any supporting libraries as we do for torch, so it's not even that useful to have around
 - most/all MI projects we'd want to use are written in torch and/or can be imported into torch easily
 - we probably don't want to use it for new projects anyway

arguments against:
 - it's a [distant] dependency of one other library (fastai, which we also don't use) so if we don't drop this library or patch out the dependency then we may as well keep it available at runtime

I think the arguments for removal are sufficiently strong that we should consider taking the actions in the 'against' column.

@cfhammill ?

**Comment by cfhammill** [comment]
I think the import speed argument is good enough in favour. Another argument against removal is if this was ever going to be used by others keeping framework options open would have been handy, but for our use keeping it is probably unnecessary

**Comment by bcdarwin** [comment]
I forgot one last justification for removal, which is that restoring in future if needed is literally a one-word change.

PR incoming.
